version: '3'
services:
  frontend:
    build:
      args:
        - node_env=production
        - node_path=./dist
    image: frontend-prod:latest
    environment:
      - PUBLIC_API_URL=http://localhost:3000
      - INTERNAL_API_URL=http://api:3000
      # - SENTRY_KEY_CLIENT=https://app.getsentry.com
      # - SENTRY_KEY_SERVER=https://app.getsentry.com
      - FACEBOOK_APP_ID=appid
      - ONE_QURAN_URL=https://one.quran.com
      - PORT=8000
