version: '3'
services:
  frontend:
    build:
      context: .
      args:
        - node_env=development
        - facebook_app_id=appid
        - assets_url=/public/
        - fonts_url=//localhost:3100/
        - public_api_url=http://api.quran.com
        - one_quran_url=https://one.quran.com
        - sentry_key_client=https://app.getsentry.com
    ports:
      - "8080:8080"
      - "8000:8000"
    # volumes:
    #  - ./src:/quran/src
    environment:
      - INTERNAL_API_URL=http://api.quran.com
      # - INTERNAL_API_URL=http://api:3000
      # - SEGMENTS_KEY=
      # - SENTRY_KEY_CLIENT=https://app.getsentry.com
      # - SENTRY_KEY_SERVER=https://app.getsentry.com
      - PORT=8000
  fonts:
    image: quran/fonts:latest
    ports:
      - "3100:3000"
