version: '3'
services:
  frontend:
    build:
      context: .
      args:
        - node_env=development
        - node_path=./src
    ports:
      - "8080:8080"
      - "8000:8000"
    #volumes:
    #  - ./src:/quran/src
    environment:
      - PUBLIC_API_URL=http://localhost:3000
      - INTERNAL_API_URL=http://staging.quran.com:3000
      # - INTERNAL_API_URL=http://api:3000
      # - SEGMENTS_KEY=
      # - SENTRY_KEY_CLIENT=https://app.getsentry.com
      # - SENTRY_KEY_SERVER=https://app.getsentry.com
      - FACEBOOK_APP_ID=appid
      - ONE_QURAN_URL=https://one.quran.com
      - PORT=8000
      - ASSET_HOST=//localhost:8000
      #- ASSET_HOST=//assets-1f14.kxcdn.com
      - FONTS_URL=//quran-1f14.kxcdn.com


